services:
  genai:
    image: onnxruntime-go-genai:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    # This service is build-only and not started
    entrypoint: ["/bin/true"]

  genai-test:
    platform: linux/amd64
    container_name: genai-test
    build:
      context: .
      dockerfile: ./test.Dockerfile
      target: genai-test
    depends_on:
      - genai
    volumes:
      - $test_folder:/test
      - $test_folder/../scripts/run-unit-tests-container.sh:/run-unit-tests-container.sh
    environment:
      - HOST_UID=$host_uid
      - CI=$CI
    command: /run-unit-tests-container.sh
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]